---
# Note for connecting metabase to newer mysql servers
#
# metabase supports mysql native authentication only
# so ensure that the mysql user can autenticate with that method
# es.: `CREATE USER 'my_user'@'%' IDENTIFIED WITH mysql_native_password BY 'my_password';`
# or start the server with `--default-authentication-plugin=mysql_native_password`

- name: Spin up metabase
  docker_container:
    name: metabase
    state: started
    image: metabase/metabase
    env:
      MB_DB_FILE: "/metabase-data/metabase.db"
      JAVA_TIMEZONE: "{{ METABASE_JAVA_TIMEZONE }}"
    ports:
      - "3000:3000"
    volumes:
      - "metabase:/metabase-data"
